### ISSUE TITLE
写真の書き出し直し

### ISSUE THREAD

**Issue by sKawashima** [YngLab/MProjectPreSite#23]
館内写真の扱いサイズが上がったしやっぱ解像度でかいの早めに頼む

**Comment by k-odashi** [comment]
使い方分かってないけど、終わったことを宣言

**Comment by k-odashi** [comment]
ところどころ、画像サイズを指定しないと表示が崩れて異能でそれの修正をお願いしたい

**Comment by sKawashima** [comment]
@k-odashi
画像コミットして欲しい
